
-- Create tables
CREATE TABLE IF NOT EXISTS questions (
    id SERIAL PRIMARY KEY,
    unit VARCHAR(255) NOT NULL,
    question TEXT NOT NULL,
    options JSONB NOT NULL,
    answer VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_test_results (
    id SERIAL PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    score INTEGER NOT NULL,
    total_questions INTEGER NOT NULL,
    completed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Clear existing data (optional, comment out if you want to append)
DELETE FROM questions;

-- Insert questions
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 1 – INTRODUCTION, TOPOLOGIES, OSI MODEL, MEDIA', 'In the OSI model, encryption and decryption are functions of the ______ layer.', '{"A":"Transport","B":"Session","C":"Presentation","D":"Application"}', 'C');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 1 – INTRODUCTION, TOPOLOGIES, OSI MODEL, MEDIA', 'The topology that involves tokens.', '{"A":"Star","B":"Ring","C":"Bus","D":"Daisy-Chaining"}', 'B');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 1 – INTRODUCTION, TOPOLOGIES, OSI MODEL, MEDIA', 'LAN interconnects hosts; WAN interconnects connecting _______.', '{"A":"Networking devices","B":"LANs","C":"PCs","D":"PANs"}', 'B');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 1 – INTRODUCTION, TOPOLOGIES, OSI MODEL, MEDIA', 'Which network topology is best suited for scenarios requiring high reliability & easy node addition?', '{"A":"Bus","B":"Mesh","C":"Star","D":"Ring"}', 'B');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 1 – INTRODUCTION, TOPOLOGIES, OSI MODEL, MEDIA', 'Which of the following is used in a typical circuit-switching network?', '{"A":"Datagram packet","B":"Virtual circuit","C":"FDM","D":"TDM"}', 'B');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 1 – INTRODUCTION, TOPOLOGIES, OSI MODEL, MEDIA', 'In the layer hierarchy, when a packet moves from upper to lower layers, headers are _____.', '{"A":"Added","B":"Removed","C":"Rearranged","D":"Modified"}', 'A');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 1 – INTRODUCTION, TOPOLOGIES, OSI MODEL, MEDIA', 'Which of the following primarily uses guided media?', '{"A":"Cellular telephone","B":"Local telephone system","C":"Satellite communication","D":"Radio broadcasting"}', 'B');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 1 – INTRODUCTION, TOPOLOGIES, OSI MODEL, MEDIA', 'What is the frequency range of coaxial cable?', '{"A":"100 KHz – 500 MHz","B":"100 MHz – 500 MHz","C":"1000 KHz – 500 MHz","D":"10 MHz – 50 MHz"}', 'A');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 1 – INTRODUCTION, TOPOLOGIES, OSI MODEL, MEDIA', '______ is a multiport repeater.', '{"A":"Hub","B":"Bridge","C":"Switch","D":"Router"}', 'C');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 1 – INTRODUCTION, TOPOLOGIES, OSI MODEL, MEDIA', 'Which transmission medium is best in high-interference environments?', '{"A":"UTP","B":"Coaxial Cable","C":"Fiber Optic","D":"STP"}', 'B');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 1 – INTRODUCTION, TOPOLOGIES, OSI MODEL, MEDIA', 'Which switching technique is used in circuit-switched networks for efficient bandwidth utilization?', '{"A":"Packet switching","B":"Message switching","C":"Frequency Division Multiplexing","D":"Time Division Multiplexing"}', 'C');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 1 – INTRODUCTION, TOPOLOGIES, OSI MODEL, MEDIA', 'What does latency define?', '{"A":"Packet loss","B":"Latency","C":"Throughput","D":"Bandwidth"}', 'B');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 1 – INTRODUCTION, TOPOLOGIES, OSI MODEL, MEDIA', 'Which protocol is an example of Exterior Gateway Protocol (EGP)?', '{"A":"OSPF","B":"IS-IS","C":"BGP","D":"RIPv1"}', 'C');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 1 – INTRODUCTION, TOPOLOGIES, OSI MODEL, MEDIA', 'Which network type best suits four computers in a shop?', '{"A":"WAN","B":"MAN","C":"PAN","D":"LAN"}', 'D');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 1 – INTRODUCTION, TOPOLOGIES, OSI MODEL, MEDIA', 'The field in the IP header used to specify how long a datagram can remain in network.', '{"A":"Identification","B":"Options","C":"Type of Service","D":"Time To Live (TTL)"}', 'D');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 1 – INTRODUCTION, TOPOLOGIES, OSI MODEL, MEDIA', 'What is the loopback address in IPv6?', '{"A":"127.0.0.1","B":"FE80::1","C":"::1","D":"255.255.255.0"}', 'C');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 1 – INTRODUCTION, TOPOLOGIES, OSI MODEL, MEDIA', 'Which technique is commonly used in wireless to avoid hidden terminal problem?', '{"A":"Aloha","B":"RTS/CTS","C":"CSMA/CD","D":"TDMA"}', 'B');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 1 – INTRODUCTION, TOPOLOGIES, OSI MODEL, MEDIA', 'What is the purpose of a default route?', '{"A":"Route packets to all networks","B":"Define a route when no specific route exists","C":"Block unknown traffic","D":"Speed up routing"}', 'B');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 1 – INTRODUCTION, TOPOLOGIES, OSI MODEL, MEDIA', 'In Distance Vector Routing, routers exchange info with ______.', '{"A":"All routers","B":"Routers < 2 hops","C":"Their neighbours","D":"Central server"}', 'C');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 2 – IP ADDRESSING, SUBNETTING, NAT, NETWORK DEVICES', 'Which technique supports virtual circuits?', '{"A":"Packet switching","B":"Virtual Circuit Switching","C":"TDM","D":"FDM"}', 'B');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 2 – IP ADDRESSING, SUBNETTING, NAT, NETWORK DEVICES', 'You are given IP 193.103.20.0/24 and need 50 subnets. How many hosts & subnets?', '{"A":"20 hosts, 50 subnets","B":"6 hosts, 64 subnets","C":"4 hosts, 50 subnets","D":"2 hosts, 64 subnets"}', 'D');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 2 – IP ADDRESSING, SUBNETTING, NAT, NETWORK DEVICES', '______ implies all subnets are derived from the same subnet mask.', '{"A":"Static Subnetting","B":"Dynamic Subnetting","C":"VLSM","D":"Dynamic Length Subnetting"}', 'A');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 2 – IP ADDRESSING, SUBNETTING, NAT, NETWORK DEVICES', 'Subnetting 172.17.32.0/23 into /27 gives how many subnets & hosts?', '{"A":"8 subnets, 31 hosts","B":"8 subnets, 32 hosts","C":"16 subnets, 30 hosts","D":"16 subnets, 32 hosts"}', 'C');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 2 – IP ADDRESSING, SUBNETTING, NAT, NETWORK DEVICES', 'If you want 12 subnets using Class C, subnet mask is:', '{"A":"255.255.255.252","B":"255.255.255.255","C":"255.255.255.240","D":"255.255.255.248"}', 'C');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 2 – IP ADDRESSING, SUBNETTING, NAT, NETWORK DEVICES', 'Given 201.14.78.65 with mask 255.255.255.224, what is subnet address?', '{"A":"201.14.78.32","B":"201.14.78.65","C":"201.14.78.64","D":"201.14.78.12"}', 'C');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 2 – IP ADDRESSING, SUBNETTING, NAT, NETWORK DEVICES', 'Class ______ has the greatest number of hosts per network.', '{"A":"A","B":"B","C":"C","D":"D"}', 'A');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 2 – IP ADDRESSING, SUBNETTING, NAT, NETWORK DEVICES', 'NAT (Network Address Translation) uses the ______ table.', '{"A":"Switch table","B":"Bridge table","C":"Server table","D":"Router translation table"}', 'D');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 2 – IP ADDRESSING, SUBNETTING, NAT, NETWORK DEVICES', 'In ARP: Finding MAC address from IP address means:', '{"A":"Find IP from DNS","B":"Find IP of gateway","C":"Find IP for MAC","D":"Find MAC for IP"}', 'D');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 2 – IP ADDRESSING, SUBNETTING, NAT, NETWORK DEVICES', 'Which config command allows 8 subnets if mask is 255.255.255.224?', '{"A":"Router(config)#ip classless","B":"Router(config)#no ip classful","C":"Router(config)#ip unnumbered","D":"Router(config)#ip subnet-zero"}', 'D');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 2 – IP ADDRESSING, SUBNETTING, NAT, NETWORK DEVICES', 'What is the broadcast address for 132.168.16.4/20?', '{"A":"132.168.31.255","B":"132.168.15.255","C":"132.168.16.255","D":"132.168.255.255"}', 'A');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 2 – IP ADDRESSING, SUBNETTING, NAT, NETWORK DEVICES', 'How many usable host addresses are available per /30 subnet?', '{"A":"2","B":"4","C":"6","D":"14"}', 'A');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 2 – IP ADDRESSING, SUBNETTING, NAT, NETWORK DEVICES', 'IPv4 class C: how many possible addresses per network?', '{"A":"65536","B":"128","C":"256","D":"512"}', 'C');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 2 – IP ADDRESSING, SUBNETTING, NAT, NETWORK DEVICES', 'The broadcast address for 10.10.10.0 with mask 255.255.255.128 is:', '{"A":"10.10.10.127","B":"10.10.10.128","C":"10.10.10.254","D":"10.10.10.255"}', 'A');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 2 – IP ADDRESSING, SUBNETTING, NAT, NETWORK DEVICES', 'How many total IPs for Network ID B in a Class B IPv4?', '{"A":"16 bits for host","B":"16 bits for network","C":"8 bits network, 24 bits host","D":"24 bits network, 8 bits host"}', 'A');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 2 – IP ADDRESSING, SUBNETTING, NAT, NETWORK DEVICES', 'From 192.168.10.0/25, how many usable hosts?', '{"A":"62","B":"64","C":"126","D":"128"}', 'A');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 2 – IP ADDRESSING, SUBNETTING, NAT, NETWORK DEVICES', 'A router receives packet for 192.168.10.8/25. How many host addresses?', '{"A":"62","B":"30","C":"126","D":"14"}', 'A');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 2 – IP ADDRESSING, SUBNETTING, NAT, NETWORK DEVICES', 'IPv6 address length is:', '{"A":"16 bit","B":"32 bit","C":"64 bit","D":"128 bit"}', 'D');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 2 – IP ADDRESSING, SUBNETTING, NAT, NETWORK DEVICES', 'The loopback address in IPv6 is:', '{"A":"127.0.0.1","B":"FE80::1","C":"::1","D":"255.255.255.0"}', 'C');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 2 – IP ADDRESSING, SUBNETTING, NAT, NETWORK DEVICES', 'Network device used to amplify signals without altering contents:', '{"A":"Switch","B":"Router","C":"Repeater","D":"Gateway"}', 'C');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 3 – ROUTING (DV, LS, RIP, OSPF, BGP, Forwarding)', 'Which device connects two LANs operating on same protocol?', '{"A":"Switch","B":"Bridge","C":"Router","D":"Modem"}', 'B');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 3 – ROUTING (DV, LS, RIP, OSPF, BGP, Forwarding)', 'Packets of the same session may be routed through different paths in:', '{"A":"TCP, but not UDP","B":"TCP and UDP","C":"UDP, but not TCP","D":"Neither TCP nor UDP"}', 'B');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 3 – ROUTING (DV, LS, RIP, OSPF, BGP, Forwarding)', 'In network of LANs connected by bridges, why is the spanning tree protocol used?', '{"A":"For shortest path routing","B":"To avoid loops in routing paths","C":"For fault tolerance","D":"For minimizing collisions"}', 'B');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 3 – ROUTING (DV, LS, RIP, OSPF, BGP, Forwarding)', 'In distance vector routing, each router receives information from:', '{"A":"Every router in network","B":"Every router < 2 hops","C":"A table stored by network","D":"Its neighbours only"}', 'D');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 3 – ROUTING (DV, LS, RIP, OSPF, BGP, Forwarding)', 'Router B receives update from A: Net1 is 2 hops away. Next update says 5 hops (RIP). Value entered?', '{"A":"2","B":"3","C":"6","D":"7"}', 'C');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 3 – ROUTING (DV, LS, RIP, OSPF, BGP, Forwarding)', 'Dijkstra’s algorithm is used to:', '{"A":"Create LSAs","B":"Flood LSAs","C":"Calculate routing tables","D":"Create link-state database"}', 'C');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 3 – ROUTING (DV, LS, RIP, OSPF, BGP, Forwarding)', 'Which is NOT a multicasting application?', '{"A":"Teleconferencing","B":"Distance learning","C":"Information dissemination","D":"Train announcements"}', 'D');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 3 – ROUTING (DV, LS, RIP, OSPF, BGP, Forwarding)', 'In CSMA/CA or MAC access methods, which has NO collision?', '{"A":"Aloha","B":"CSMA/CD","C":"CSMA/CA","D":"Token passing"}', 'D');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 3 – ROUTING (DV, LS, RIP, OSPF, BGP, Forwarding)', 'Maximum window size in Selective Repeat with n-bit sequence number is:', '{"A":"2^n","B":"2^(n−1)","C":"2^n − 1","D":"2^(n−2)"}', 'D');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 3 – ROUTING (DV, LS, RIP, OSPF, BGP, Forwarding)', 'Sliding window protocol works on:', '{"A":"No duplex","B":"Half duplex","C":"Full duplex","D":"Single duplex"}', 'C');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 3 – ROUTING (DV, LS, RIP, OSPF, BGP, Forwarding)', 'What algorithm is used by Link-State routing to compute shortest path?', '{"A":"Floyd-Warshall","B":"Bellman-Ford","C":"A*","D":"Dijkstra"}', 'D');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 3 – ROUTING (DV, LS, RIP, OSPF, BGP, Forwarding)', 'What is an example of Path Vector Routing Protocol?', '{"A":"BGP","B":"RIP v1","C":"OSPF","D":"RIP v2"}', 'A');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 3 – ROUTING (DV, LS, RIP, OSPF, BGP, Forwarding)', 'Which attribute is used by BGP to choose best path among multiple AS paths?', '{"A":"Hop count","B":"Throughput","C":"AS Path","D":"Delay"}', 'C');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 3 – ROUTING (DV, LS, RIP, OSPF, BGP, Forwarding)', 'In Distance Vector Routing, how are routing loops prevented?', '{"A":"Periodic HELLO messages","B":"Split Horizon","C":"Link state advertisement","D":"Spanning Tree"}', 'B');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 3 – ROUTING (DV, LS, RIP, OSPF, BGP, Forwarding)', 'Which routing protocol is known for fast convergence and is Cisco proprietary?', '{"A":"EIGRP","B":"OSPF","C":"RIP","D":"BGP"}', 'A');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 3 – ROUTING (DV, LS, RIP, OSPF, BGP, Forwarding)', 'What is the primary function of a default route in routing?', '{"A":"Route packets to all networks","B":"Define a route when no route is found","C":"Block unknown traffic","D":"Improve convergence"}', 'B');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 3 – ROUTING (DV, LS, RIP, OSPF, BGP, Forwarding)', 'First step taken by a router in link-state routing after detecting topology change?', '{"A":"Updates routing table","B":"Waits for neighbours","C":"Calculates shortest path","D":"Floods LSA"}', 'D');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 3 – ROUTING (DV, LS, RIP, OSPF, BGP, Forwarding)', 'Which protocol is used by routers exchanging distance vector info?', '{"A":"BGP","B":"RIP","C":"OSPF","D":"STP"}', 'B');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 3 – ROUTING (DV, LS, RIP, OSPF, BGP, Forwarding)', 'Which field determines the maximum hop count for TTL expiration?', '{"A":"Version","B":"IHL","C":"TOS","D":"TTL"}', 'D');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 3 – ROUTING (DV, LS, RIP, OSPF, BGP, Forwarding)', 'In Path Vector Routing, routers maintain:', '{"A":"Entire network topology","B":"Distance tables","C":"AS-path list","D":"Neighbour list"}', 'C');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 4 – MAC, CSMA/CD, CSMA/CA, ARQ, CRC, ERROR CONTROL', 'Which protocol requires router to broadcast complete routing table every 30 seconds?', '{"A":"OSPF","B":"RIP","C":"BGP","D":"STP"}', 'B');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 4 – MAC, CSMA/CD, CSMA/CA, ARQ, CRC, ERROR CONTROL', 'In CSMA/CD, when a device detects a collision it:', '{"A":"Immediately retransmits","B":"Stops transmitting & sends a jamming signal","C":"Reduces power & continues","D":"Waits fixed time and retransmits"}', 'B');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 4 – MAC, CSMA/CD, CSMA/CA, ARQ, CRC, ERROR CONTROL', 'What does a device do in CSMA/CD after sending a jamming signal?', '{"A":"Retransmits immediately","B":"Uses binary exponential backoff","C":"Drops the frame permanently","D":"Sends ACK"}', 'B');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 4 – MAC, CSMA/CD, CSMA/CA, ARQ, CRC, ERROR CONTROL', 'In CSMA/CA, which technique helps avoid collisions?', '{"A":"RFD","B":"RTS/CTS","C":"Token passing","D":"FDM"}', 'B');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 4 – MAC, CSMA/CD, CSMA/CA, ARQ, CRC, ERROR CONTROL', 'Which access method has NO collision?', '{"A":"ALOHA","B":"CSMA/CD","C":"CSMA/CA","D":"Token Passing"}', 'D');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 4 – MAC, CSMA/CD, CSMA/CA, ARQ, CRC, ERROR CONTROL', 'What is the primary function of the MAC address in Ethernet?', '{"A":"Encrypt frame","B":"Segment data","C":"Identify source & destination inside LAN","D":"Route frame to correct IP"}', 'C');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 4 – MAC, CSMA/CD, CSMA/CA, ARQ, CRC, ERROR CONTROL', 'Hamming distance between 101010 and 100100 is:', '{"A":"2","B":"3","C":"4","D":"5"}', 'B');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 4 – MAC, CSMA/CD, CSMA/CA, ARQ, CRC, ERROR CONTROL', 'In Stop-and-Wait ARQ, how many packets can be sent before ACK?', '{"A":"0","B":"1","C":"n","D":"n–1"}', 'B');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 4 – MAC, CSMA/CD, CSMA/CA, ARQ, CRC, ERROR CONTROL', 'Sliding Window ARQ allows sending multiple packets before ACK.', '{"A":"Stop-and-Wait","B":"Sliding Window","C":"HDLC","D":"PPP"}', 'B');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 4 – MAC, CSMA/CD, CSMA/CA, ARQ, CRC, ERROR CONTROL', 'In Selective Repeat ARQ, max window size (n-bit seq no.) is:', '{"A":"2ⁿ","B":"2ⁿ−1","C":"2ⁿ−2","D":"2ⁿ⁻¹"}', 'C');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 4 – MAC, CSMA/CD, CSMA/CA, ARQ, CRC, ERROR CONTROL', 'Flow control prevents:', '{"A":"Bit errors","B":"Receiver buffer overflow","C":"Sender buffer overflow","D":"Collision"}', 'B');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 4 – MAC, CSMA/CD, CSMA/CA, ARQ, CRC, ERROR CONTROL', 'The maximum number of unacknowledged frames in Stop-and-Wait is:', '{"A":"0","B":"1","C":"n","D":"2"}', 'A');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 4 – MAC, CSMA/CD, CSMA/CA, ARQ, CRC, ERROR CONTROL', 'HDLC stands for:', '{"A":"High-level data link control","B":"Half duplex line communication","C":"High duplex line control","D":"Host data link control"}', 'A');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 4 – MAC, CSMA/CD, CSMA/CA, ARQ, CRC, ERROR CONTROL', 'Pure ALOHA efficiency is:', '{"A":"18.4%","B":"36.8%","C":"50%","D":"100%"}', 'A');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 4 – MAC, CSMA/CD, CSMA/CA, ARQ, CRC, ERROR CONTROL', 'In Ethernet minimum frame size requirement is due to:', '{"A":"CRC","B":"Collision detection","C":"Propagation delay","D":"MAC address size"}', 'B');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 4 – MAC, CSMA/CD, CSMA/CA, ARQ, CRC, ERROR CONTROL', 'CSMA/CD is used in which LAN type?', '{"A":"Token Ring","B":"Wi-Fi","C":"Ethernet","D":"Bluetooth"}', 'C');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 4 – MAC, CSMA/CD, CSMA/CA, ARQ, CRC, ERROR CONTROL', 'Token Ring maximum ring uses:', '{"A":"CSMA/CD","B":"Token Passing","C":"RTS/CTS","D":"Polling"}', 'B');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 4 – MAC, CSMA/CD, CSMA/CA, ARQ, CRC, ERROR CONTROL', 'CRC can detect:', '{"A":"All single-bit errors","B":"All double-bit errors","C":"All burst errors < polynomial length","D":"All errors"}', 'C');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 4 – MAC, CSMA/CD, CSMA/CA, ARQ, CRC, ERROR CONTROL', 'Condition to detect odd number of bit errors using CRC:', '{"A":"G(x) has odd number of terms","B":"1+x is factor of G(x)","C":"G(x) contains more than two terms","D":"G(x) does not divide M(x)"}', 'B');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 4 – MAC, CSMA/CD, CSMA/CA, ARQ, CRC, ERROR CONTROL', 'Checksum detects:', '{"A":"Single-bit errors","B":"Burst errors","C":"All odd-bit errors","D":"All even-bit errors"}', 'A');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 5 – TRANSPORT LAYER & APPLICATION LAYER (TCP, UDP, DNS, HTTP, EMAIL)', 'In CSMA/CA, ACK is used to:', '{"A":"Detect collision","B":"Confirm frame reception","C":"Reduce noise","D":"Increase throughput"}', 'B');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 5 – TRANSPORT LAYER & APPLICATION LAYER (TCP, UDP, DNS, HTTP, EMAIL)', 'UDP needs the ______ to deliver user datagram to the correct application.', '{"A":"Application address","B":"MAC address","C":"IP address","D":"Port number"}', 'D');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 5 – TRANSPORT LAYER & APPLICATION LAYER (TCP, UDP, DNS, HTTP, EMAIL)', 'Which protocol is commonly used with UDP for real-time applications?', '{"A":"HTTP","B":"FTP","C":"RTP","D":"SMTP"}', 'C');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 5 – TRANSPORT LAYER & APPLICATION LAYER (TCP, UDP, DNS, HTTP, EMAIL)', 'What mechanism does TCP use to ensure reliable data transmission?', '{"A":"TTL","B":"Retransmission of lost packets","C":"Packet filtering","D":"Encryption"}', 'B');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 5 – TRANSPORT LAYER & APPLICATION LAYER (TCP, UDP, DNS, HTTP, EMAIL)', 'Which HTTP status code means “OK / request successful”?', '{"A":"200","B":"404","C":"500","D":"301"}', 'A');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 5 – TRANSPORT LAYER & APPLICATION LAYER (TCP, UDP, DNS, HTTP, EMAIL)', 'Which protocol does Telnet use?', '{"A":"ICMP","B":"UDP","C":"IP","D":"TCP"}', 'D');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 5 – TRANSPORT LAYER & APPLICATION LAYER (TCP, UDP, DNS, HTTP, EMAIL)', 'Which transport protocol is used in electronic mail transfer (SMTP)?', '{"A":"SMTP","B":"STCP","C":"TCP","D":"UDP"}', 'C');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 5 – TRANSPORT LAYER & APPLICATION LAYER (TCP, UDP, DNS, HTTP, EMAIL)', 'The well-known port number defines the ______.', '{"A":"Client program","B":"Server program","C":"Device ID","D":"MAC address"}', 'B');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 5 – TRANSPORT LAYER & APPLICATION LAYER (TCP, UDP, DNS, HTTP, EMAIL)', 'To prevent “silly window syndrome”, which technique can be used?', '{"A":"Nagle’s algorithm","B":"Clark’s solution","C":"Delayed ACK","D":"Zero timer"}', 'B');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 5 – TRANSPORT LAYER & APPLICATION LAYER (TCP, UDP, DNS, HTTP, EMAIL)', 'A client performs socket() and connect() while server has not called accept(). What happens?', '{"A":"connect() returns success","B":"connect() blocks","C":"connect() errors","D":"connect() creates core dump"}', 'B');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 5 – TRANSPORT LAYER & APPLICATION LAYER (TCP, UDP, DNS, HTTP, EMAIL)', 'Maximum data size application layer can send to TCP?', '{"A":"Any size","B":"2¹⁶ – header size","C":"2³¹ bytes","D":"1500 bytes"}', 'A');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 5 – TRANSPORT LAYER & APPLICATION LAYER (TCP, UDP, DNS, HTTP, EMAIL)', 'Which DNS record maps hostname → IP address?', '{"A":"MX","B":"CNAME","C":"A","D":"PTR"}', 'C');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 5 – TRANSPORT LAYER & APPLICATION LAYER (TCP, UDP, DNS, HTTP, EMAIL)', 'Which DNS record is used for mail servers?', '{"A":"A","B":"NS","C":"MX","D":"SOA"}', 'C');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 5 – TRANSPORT LAYER & APPLICATION LAYER (TCP, UDP, DNS, HTTP, EMAIL)', 'What is used in email architecture for transferring messages between mail servers?', '{"A":"POP3","B":"IMAP","C":"SMTP","D":"HTTP"}', 'C');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 5 – TRANSPORT LAYER & APPLICATION LAYER (TCP, UDP, DNS, HTTP, EMAIL)', 'POP3 is mainly used for:', '{"A":"Sending mail","B":"Receiving & downloading mail","C":"Managing mailboxes on server","D":"Spam filtering"}', 'B');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 5 – TRANSPORT LAYER & APPLICATION LAYER (TCP, UDP, DNS, HTTP, EMAIL)', 'IMAP is used to:', '{"A":"Receive & delete mail only","B":"Manage mail remotely on server","C":"Forward mails","D":"Encrypt mails"}', 'B');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 5 – TRANSPORT LAYER & APPLICATION LAYER (TCP, UDP, DNS, HTTP, EMAIL)', 'Which protocol is connection-oriented?', '{"A":"UDP","B":"ICMP","C":"TCP","D":"ARP"}', 'C');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 5 – TRANSPORT LAYER & APPLICATION LAYER (TCP, UDP, DNS, HTTP, EMAIL)', 'Which header field ensures reliable TCP sequencing?', '{"A":"ACK number","B":"Sequence number","C":"Window size","D":"URG pointer"}', 'B');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 5 – TRANSPORT LAYER & APPLICATION LAYER (TCP, UDP, DNS, HTTP, EMAIL)', 'TCP handshake uses how many steps?', '{"A":"2","B":"3","C":"4","D":"5"}', 'B');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 5 – TRANSPORT LAYER & APPLICATION LAYER (TCP, UDP, DNS, HTTP, EMAIL)', 'TCP connection termination uses:', '{"A":"2-way","B":"3-way","C":"4-way","D":"5-way"}', 'C');
INSERT INTO questions (unit, question, options, answer) VALUES ('UNIT 5 – TRANSPORT LAYER & APPLICATION LAYER (TCP, UDP, DNS, HTTP, EMAIL)', 'DNS uses which transport protocol?', '{"A":"Only TCP","B":"Only UDP","C":"Both TCP and UDP","D":"ICMP"}', 'C');
